apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quinta-web
  namespace: quinta
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  rules:
    - host: quinta.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: quinta-web
                port:
                  number: 80
